// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD0Tz7y3lf_yhu12j7msfquYlLpNqFxIWE",
    appId: "1:775856893434:web:f1bcfd490673e637afc843",
    messagingSenderId: "775856893434",
    projectId: "patinka-657",
    authDomain: "patinka-657.firebaseapp.com",
    storageBucket: "patinka-657.appspot.com",
    measurementId: "G-LS2XXJGN4K",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCs-5Gxq2xzz7ijdpHbIwkbyqmISKlyp6A",
    appId: "1:775856893434:android:eb53f68cc729a661afc843",
    messagingSenderId: "775856893434",
    projectId: "patinka-657",
    storageBucket: "patinka-657.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAOIgKSJdY38JkuPaHD9uFk41jNJbazjYk",
    appId: "1:775856893434:ios:28720d88fae0d30fafc843",
    messagingSenderId: "775856893434",
    projectId: "patinka-657",
    storageBucket: "patinka-657.appspot.com",
    iosClientId:
        "775856893434-1thgd9vo3m5eqe1qji53mthc7lqkj3o4.apps.googleusercontent.com",
    iosBundleId: "com.olwin.patinka",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAOIgKSJdY38JkuPaHD9uFk41jNJbazjYk",
    appId: "1:775856893434:ios:28720d88fae0d30fafc843",
    messagingSenderId: "775856893434",
    projectId: "patinka-657",
    storageBucket: "patinka-657.appspot.com",
    iosClientId:
        "775856893434-1thgd9vo3m5eqe1qji53mthc7lqkj3o4.apps.googleusercontent.com",
    iosBundleId: "com.olwin.patinka",
  );
}
